#!/usr/bin/env node
/**
 * sync-blog.mjs — fetches the Jekyll Atom feed, maps entries to the
 * { title, date, preview, url, tags }[] shape, and writes src/data/blog.js.
 *
 * Idempotent: re-running with an unchanged feed produces the same output.
 * Run manually or let .github/workflows/sync-blog.yml call it on schedule.
 */

import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { XMLParser } from 'fast-xml-parser';

const FEED_URL = 'https://tejalgoyal2.github.io/feed.xml';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/data/blog.js');

// ── Fetch ─────────────────────────────────────────────────────────────────────
async function fetchFeed() {
  const res = await fetch(FEED_URL, { headers: { 'User-Agent': 'portfolio-sync/1.0' } });
  if (!res.ok) throw new Error(`Feed fetch failed: ${res.status} ${res.statusText}`);
  return res.text();
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function stripHtml(html) {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#039;/g, "'")
    .replace(/&[a-z]+;/gi, ' ').replace(/&#\d+;/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function formatDate(isoStr) {
  // Extract YYYY-MM-DD from any ISO-8601 string
  const m = String(isoStr ?? '').match(/(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : '';
}

function coerceString(val) {
  if (val == null) return '';
  if (typeof val === 'string') return val;
  if (typeof val === 'object') return val['#text'] ?? val['_'] ?? String(val);
  return String(val);
}

// ── Map one Atom <entry> to the portfolio post shape ─────────────────────────
function parseEntry(entry) {
  // title
  const title = stripHtml(coerceString(entry.title)).replace(/\s+/g, ' ').trim();

  // url — Atom <link rel="alternate" href="..."/> or plain <link>
  let url = '';
  if (entry.link) {
    const links = Array.isArray(entry.link) ? entry.link : [entry.link];
    const alt = links.find(l => l['@_rel'] === 'alternate' || l['@_rel'] == null) ?? links[0];
    url = alt?.['@_href'] ?? coerceString(alt);
  }

  // date — prefer published over updated
  const date = formatDate(entry.published ?? entry.updated ?? '');

  // preview — prefer summary; fall back to first ~160 chars of content
  let preview = '';
  const summaryRaw = coerceString(entry.summary ?? entry['content:encoded'] ?? entry.content ?? '');
  if (summaryRaw) {
    preview = stripHtml(summaryRaw);
    if (preview.length > 160) preview = preview.slice(0, 160).replace(/\s+\S*$/, '').trimEnd() + '…';
  }

  // tags — Atom <category term="..."/>
  const tags = [];
  if (entry.category) {
    const cats = Array.isArray(entry.category) ? entry.category : [entry.category];
    for (const c of cats) {
      const term = c['@_term'] ?? c['@_label'] ?? coerceString(c);
      if (term && !tags.includes(term)) tags.push(term);
    }
  }

  return { title, date, preview, url, tags };
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`Fetching ${FEED_URL}…`);
  const xml = await fetchFeed();

  const parser = new XMLParser({
    ignoreAttributes: false,
    attributeNamePrefix: '@_',
    parseAttributeValue: false,
    trimValues: true,
    parseTagValue: true,
    htmlEntities: true,
  });
  const doc = parser.parse(xml);

  // Support both Atom (<feed><entry>) and RSS 2.0 (<rss><channel><item>)
  const feed = doc.feed ?? doc.rss?.channel;
  if (!feed) throw new Error('Could not locate feed root — check feed format');

  const rawEntries = feed.entry ?? feed.item ?? [];
  const entries = Array.isArray(rawEntries) ? rawEntries : [rawEntries];

  const posts = entries
    .map(parseEntry)
    .filter(p => p.title && p.url && p.date)
    .sort((a, b) => b.date.localeCompare(a.date)); // newest first

  if (posts.length === 0) throw new Error('No posts parsed — feed may be empty or format changed');
  console.log(`Parsed ${posts.length} post(s).`);

  // Produce stable output: sorted, 2-space JSON
  const body = JSON.stringify(posts, null, 2);
  const js = [
    '// AUTO-GENERATED by scripts/sync-blog.mjs — do not edit by hand.',
    `// Last synced: ${new Date().toISOString()}`,
    '',
    'export const BLOG_POSTS = ' + body + ';',
    '',
  ].join('\n');

  await writeFile(OUT_PATH, js, 'utf8');
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch(err => {
  console.error('sync-blog error:', err.message);
  process.exit(1);
});
